language: node_js
cache: yarn
node_js:
  - 10
os: linux
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg -y
